//! Somewhere of its own for each hub's data.
//!
//! Until now the farm passed no database configuration at all to the hubs it
//! spawned, so every one of them fell back to the same default URL and **they
//! all shared a single database** — each reading and writing every other
//! community's channels, users and messages. The code even logged a warning
//! per spawn saying so. `hubs.db_path` was a SQLite-era file path nothing
//! consumed.
//!
//! Two layouts, chosen by the farm's `hub_isolation` setting:
//!
//! - **`database`** (default) — one database per hub. Best separation, and
//!   what you want when the farm's role can create databases.
//! - **`schema`** — one PostgreSQL schema per hub inside the farm's own
//!   database, selected through `search_path` on the connection. For operators
//!   who have exactly one database and no `CREATEDB` right, which is the
//!   normal shape of a managed PostgreSQL plan. Without this the farm cannot
//!   create a single hub in those environments.
//!
//! The hub needs no idea which is in use: its SQL names tables unqualified, so
//! `search_path` places them without a line of hub code changing.
//!
//! **Provisioning failure refuses the hub.** Falling back to the shared default
//! is what produced the original bug, and it produced it silently: a hub that
//! cannot get a place of its own is not started at all.
//!
//! What neither layout gives you on its own: **containment of a hostile hub.**
//! Under `hub_db_role = 'shared'` every hub connects with the farm's role, so a
//! compromised hub process can reach its siblings' data either way. That is
//! what `per_hub` is for — a login role per hub, granted its own database or
//! schema and nothing else. Orthogonal to the layout above, and so a separate
//! setting: it works with both.
//!
//! `shared` stays the default because a role per hub needs `CREATEROLE`, and
//! the managed plans `schema` exists for do not hand that out either.

use anyhow::{bail, Context, Result};
use sqlx::PgPool;

/// How a farm separates its hubs' data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Isolation {
    /// One database per hub. Requires `CREATEDB`.
    Database,
    /// One schema per hub inside the farm's database.
    Schema,
}

impl Isolation {
    /// Parse the stored setting. Anything unrecognised is treated as the
    /// default rather than failing — a farm must still start.
    pub fn from_setting(value: &str) -> Self {
        match value {
            "schema" => Isolation::Schema,
            _ => Isolation::Database,
        }
    }
}

/// Database name for a hub row id. Ids are farm-generated hex, so this is
/// always a safe identifier — asserted below rather than assumed.
pub fn database_name(hub_id: &str) -> String {
    format!("wavvon_hub_{hub_id}")
}

/// Schema name for a hub row id, in `schema` isolation.
pub fn schema_name(hub_id: &str) -> String {
    format!("hub_{hub_id}")
}

/// True when `hub_id` is safe to interpolate into an identifier.
///
/// `CREATE DATABASE` takes no bind parameters, so the name has to be formatted
/// in. Hub ids are generated by `generate_hub_id()` as hex and can never fail
/// this — the check is here so that a future change to id generation breaks
/// loudly here instead of quietly becoming an injection point.
fn is_safe_id(hub_id: &str) -> bool {
    !hub_id.is_empty()
        && hub_id.len() <= 40
        && hub_id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Rewrite a PostgreSQL URL to point at a different database on the same
/// server, preserving user, password, host, port and any query parameters
/// (`?sslmode=require` and friends).
pub fn with_database(base_url: &str, database: &str) -> Result<String> {
    let mut url = url::Url::parse(base_url).context("WAVVON_DATABASE_URL is not a valid URL")?;
    url.set_path(database);
    Ok(url.to_string())
}

/// Create this hub's database if it does not exist, and return its URL.
///
/// Idempotent: an existing database is reused, so a re-spawn or a restart
/// after a crash does not fail and does not wipe anything.
pub async fn provision_hub_database(
    farm_pool: &PgPool,
    base_url: &str,
    hub_id: &str,
) -> Result<String> {
    if !is_safe_id(hub_id) {
        bail!("hub id {hub_id:?} is not a safe database identifier");
    }
    let name = database_name(hub_id);

    let exists: Option<i32> = sqlx::query_scalar("SELECT 1 FROM pg_database WHERE datname = $1")
        .bind(&name)
        .fetch_optional(farm_pool)
        .await
        .context("could not check whether the hub database already exists")?;

    if exists.is_none() {
        // Quoted so a name that ever collides with a keyword still works.
        sqlx::query(&format!("CREATE DATABASE \"{name}\""))
            .execute(farm_pool)
            .await
            .with_context(|| {
                format!(
                    "could not create database {name}. The role the farm connects as needs \
                     CREATEDB, or hubs would have to share one database — which is the bug \
                     this replaced."
                )
            })?;
        tracing::info!(hub_id, database = %name, "Provisioned hub database");
    }

    with_database(base_url, &name)
}

/// Add a `search_path` to a PostgreSQL URL so every unqualified name in the
/// session resolves inside `schema`.
///
/// This is the whole of what makes schema isolation invisible to the hub: it
/// writes `CREATE TABLE channels` and PostgreSQL puts it in the right place.
/// `public` stays on the path so extensions installed there keep resolving.
pub fn with_schema(base_url: &str, schema: &str) -> Result<String> {
    let mut url = url::Url::parse(base_url).context("WAVVON_DATABASE_URL is not a valid URL")?;
    // libpq's `options` parameter, url-encoded by the Url writer.
    let existing: Vec<(String, String)> = url
        .query_pairs()
        .filter(|(k, _)| k != "options")
        .map(|(k, v)| (k.into_owned(), v.into_owned()))
        .collect();
    url.query_pairs_mut().clear();
    for (k, v) in existing {
        url.query_pairs_mut().append_pair(&k, &v);
    }
    url.query_pairs_mut()
        .append_pair("options", &format!("-c search_path={schema},public"));
    Ok(url.to_string())
}

/// Create this hub's schema if absent, and return a URL scoped to it.
pub async fn provision_hub_schema(
    farm_pool: &PgPool,
    base_url: &str,
    hub_id: &str,
) -> Result<String> {
    if !is_safe_id(hub_id) {
        bail!("hub id {hub_id:?} is not a safe schema identifier");
    }
    let schema = schema_name(hub_id);

    sqlx::query(&format!("CREATE SCHEMA IF NOT EXISTS \"{schema}\""))
        .execute(farm_pool)
        .await
        .with_context(|| {
            format!(
                "could not create schema {schema}. The role the farm connects as needs CREATE \
                 on this database, or hubs would have to share one namespace — which is the bug \
                 this replaced."
            )
        })?;

    with_schema(base_url, &schema)
}

/// Give this hub somewhere of its own, in whichever layout the farm uses.
pub async fn provision_hub(
    farm_pool: &PgPool,
    base_url: &str,
    hub_id: &str,
    isolation: Isolation,
) -> Result<String> {
    match isolation {
        Isolation::Database => provision_hub_database(farm_pool, base_url, hub_id).await,
        Isolation::Schema => provision_hub_schema(farm_pool, base_url, hub_id).await,
    }
}

// ---------------------------------------------------------------------------
// A PostgreSQL role per hub
// ---------------------------------------------------------------------------

/// Which credentials a spawned hub connects with.
///
/// Neither isolation layout contains a *hostile* hub on its own: a database
/// and a schema each stop hubs colliding, not one hub reading another's data,
/// because every hub connects as the farm's own role. A role per hub, granted
/// only its own space, is the part that contains it — and it works with either
/// layout, which is why it is a separate setting rather than a third value of
/// `hub_isolation`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RoleMode {
    /// Every hub connects as the farm's role. What farms did before this
    /// existed, and still the default: a role per hub needs `CREATEROLE`, and
    /// a managed plan that granted one database rarely grants that too.
    Shared,
    /// Each hub gets its own login role, granted its own database or schema
    /// and nothing else.
    PerHub,
}

impl RoleMode {
    /// Anything unrecognised is the conservative value: a farm must still
    /// start, and starting with fewer privileges than intended is the safe
    /// direction — it fails visibly at spawn rather than silently widening
    /// access.
    pub fn from_setting(value: &str) -> Self {
        match value {
            "per_hub" => RoleMode::PerHub,
            _ => RoleMode::Shared,
        }
    }
}

/// Login role for a hub row id. Same derivation as the database name, in a
/// different namespace — PostgreSQL keeps roles and databases apart.
pub fn role_name(hub_id: &str) -> String {
    format!("wavvon_hub_{hub_id}")
}

/// A password for a hub's role: 32 hex characters from the OS RNG.
///
/// Hex on purpose. It goes into `CREATE ROLE ... PASSWORD '<literal>'`, which
/// takes no bind parameters, and an alphabet with no quote in it cannot end
/// the literal early. `assert_password_is_literal_safe` holds the line if the
/// alphabet ever changes.
fn generate_password() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut bytes);
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn is_literal_safe(password: &str) -> bool {
    !password.is_empty() && password.chars().all(|c| c.is_ascii_alphanumeric())
}

/// Rewrite a PostgreSQL URL to connect as a different role.
pub fn with_credentials(base_url: &str, user: &str, password: &str) -> Result<String> {
    let mut url = url::Url::parse(base_url).context("hub database URL is not a valid URL")?;
    url.set_username(user)
        .map_err(|_| anyhow::anyhow!("cannot set a username on {base_url}"))?;
    url.set_password(Some(password))
        .map_err(|_| anyhow::anyhow!("cannot set a password on {base_url}"))?;
    Ok(url.to_string())
}

/// The database a URL points at, without the leading slash.
fn database_of(url: &str) -> Result<String> {
    let parsed = url::Url::parse(url).context("database URL is not a valid URL")?;
    Ok(parsed.path().trim_start_matches('/').to_string())
}

/// Create (or re-password) this hub's login role and grant it exactly its own
/// space, returning a URL that connects as it.
///
/// Idempotent, and safe to call for a hub that already exists: the role is
/// re-passworded rather than left with a credential nobody holds any more.
/// `hub_url` is the URL `provision_hub` just produced — the right database in
/// `database` isolation, the right `search_path` in `schema` isolation.
pub async fn provision_hub_role(
    farm_pool: &PgPool,
    admin_url: &str,
    hub_url: &str,
    hub_id: &str,
    isolation: Isolation,
) -> Result<String> {
    if !is_safe_id(hub_id) {
        bail!("hub id {hub_id:?} is not a safe role identifier");
    }
    let role = role_name(hub_id);
    let password = generate_password();
    if !is_literal_safe(&password) {
        bail!("generated password is not safe to inline into CREATE ROLE");
    }

    let exists: Option<i32> = sqlx::query_scalar("SELECT 1 FROM pg_roles WHERE rolname = $1")
        .bind(&role)
        .fetch_optional(farm_pool)
        .await
        .context("could not check whether the hub role already exists")?;

    let statement = if exists.is_some() {
        format!("ALTER ROLE \"{role}\" WITH LOGIN PASSWORD '{password}'")
    } else {
        format!("CREATE ROLE \"{role}\" LOGIN PASSWORD '{password}'")
    };
    sqlx::query(&statement)
        .execute(farm_pool)
        .await
        .with_context(|| {
            format!(
                "could not create role {role}. The role the farm connects as needs CREATEROLE \
                 for hub_db_role = 'per_hub'; leave it 'shared' where that right is not available."
            )
        })?;

    match isolation {
        Isolation::Database => {
            let database = database_of(hub_url)?;
            // Nobody but this hub may even connect. Without the REVOKE the
            // grant below is decoration: PUBLIC has CONNECT on a new database
            // by default, so every sibling role could open it.
            for sql in [
                format!("REVOKE ALL ON DATABASE \"{database}\" FROM PUBLIC"),
                format!("GRANT ALL PRIVILEGES ON DATABASE \"{database}\" TO \"{role}\""),
            ] {
                sqlx::query(&sql)
                    .execute(farm_pool)
                    .await
                    .with_context(|| format!("could not grant {database} to {role}"))?;
            }

            // The hub creates its own tables, so it needs CREATE on the schema
            // they land in — and that grant lives *inside* the hub's database,
            // which the farm's pool is not connected to.
            let admin_in_hub_db = with_database(admin_url, &database)?;
            let conn = PgPool::connect(&admin_in_hub_db)
                .await
                .with_context(|| format!("could not connect to {database} to grant its schema"))?;
            let granted = sqlx::query(&format!("GRANT ALL ON SCHEMA public TO \"{role}\""))
                .execute(&conn)
                .await;
            conn.close().await;
            granted.with_context(|| format!("could not grant schema public in {database}"))?;
        }
        Isolation::Schema => {
            let schema = schema_name(hub_id);
            let database = database_of(admin_url)?;
            for sql in [
                format!("GRANT CONNECT ON DATABASE \"{database}\" TO \"{role}\""),
                format!("REVOKE ALL ON SCHEMA \"{schema}\" FROM PUBLIC"),
                format!("GRANT ALL ON SCHEMA \"{schema}\" TO \"{role}\""),
            ] {
                sqlx::query(&sql)
                    .execute(farm_pool)
                    .await
                    .with_context(|| format!("could not grant schema {schema} to {role}"))?;
            }
        }
    }

    tracing::info!(hub_id, role = %role, "Provisioned a role for the hub");
    with_credentials(hub_url, &role, &password)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn database_name_is_derived_from_the_hub_id() {
        assert_eq!(database_name("a1b2c3d4"), "wavvon_hub_a1b2c3d4");
    }

    #[test]
    fn safe_ids_are_hex_like_and_bounded() {
        assert!(is_safe_id("a1b2c3d4"));
        assert!(is_safe_id("hub-1_x"));
        assert!(!is_safe_id(""));
        assert!(!is_safe_id(&"a".repeat(41)));
    }

    /// The check exists so a future id format cannot quietly become an
    /// injection point in the one statement that takes no bind parameters.
    #[test]
    fn ids_that_could_break_out_of_an_identifier_are_refused() {
        assert!(!is_safe_id("a\"; DROP DATABASE postgres; --"));
        assert!(!is_safe_id("has space"));
        assert!(!is_safe_id("quote\"inside"));
    }

    #[test]
    fn with_database_swaps_only_the_database_name() {
        assert_eq!(
            with_database("postgres://u:p@host:5432/farm", "wavvon_hub_x").unwrap(),
            "postgres://u:p@host:5432/wavvon_hub_x"
        );
    }

    #[test]
    fn schema_name_is_derived_from_the_hub_id() {
        assert_eq!(schema_name("a1b2c3d4"), "hub_a1b2c3d4");
    }

    #[test]
    fn isolation_defaults_to_database_for_anything_unexpected() {
        assert_eq!(Isolation::from_setting("schema"), Isolation::Schema);
        assert_eq!(Isolation::from_setting("database"), Isolation::Database);
        assert_eq!(Isolation::from_setting("nonsense"), Isolation::Database);
        assert_eq!(Isolation::from_setting(""), Isolation::Database);
    }

    /// The one line that makes schema isolation invisible to the hub: it keeps
    /// writing unqualified names and PostgreSQL puts them in the right place.
    #[test]
    fn with_schema_sets_the_search_path_and_keeps_public_on_it() {
        let out = with_schema("postgres://u:p@host:5432/farm", "hub_x").unwrap();
        assert!(out.contains("options="), "got {out}");
        let decoded = out
            .replace("%20", " ")
            .replace("%3D", "=")
            .replace("%2C", ",");
        assert!(
            decoded.contains("search_path=hub_x,public"),
            "got {decoded}"
        );
    }

    #[test]
    fn with_schema_keeps_other_parameters_and_replaces_only_options() {
        let once = with_schema("postgres://u:p@host/farm?sslmode=require", "hub_x").unwrap();
        assert!(once.contains("sslmode=require"), "got {once}");

        // Applying it twice must not stack two `options` parameters — the
        // second would be ignored or, worse, the first would be.
        let twice = with_schema(&once, "hub_y").unwrap();
        assert_eq!(twice.matches("options=").count(), 1, "got {twice}");
        let decoded = twice
            .replace("%20", " ")
            .replace("%3D", "=")
            .replace("%2C", ",");
        assert!(
            decoded.contains("search_path=hub_y,public"),
            "got {decoded}"
        );
    }

    /// Connection parameters are not decoration — dropping `sslmode` would
    /// turn a required-TLS setup into a silent plaintext one.
    #[test]
    fn with_database_preserves_query_parameters() {
        let out = with_database(
            "postgres://u:p@host:5432/farm?sslmode=require",
            "wavvon_hub_x",
        )
        .unwrap();
        assert!(out.contains("wavvon_hub_x"), "got {out}");
        assert!(out.contains("sslmode=require"), "got {out}");
    }
}
